defaults:
  - datasets: data2025
  - models: lightgbm
  - experiments: 2025_dev
  - _self_

seed: 42

hydra:
  job_logging:
    version: 1
    root:
      level: DEBUG
      handlers: [console]
  hydra_logging:
    level: DEBUG

results:
  save_path: "reports/${experiments.experiment_name}/${models.model_name}/${datasets.dataset_name}/${experiments.optimization_parameters.model}/${experiments.optimization_parameters.cvar_limit}/"
