dataset_name: "data2025_DE_LU"

type: pandas.ParquetDataSet
filename: data2025_DE_LU.parquet
filepath: "data/processed/"
load_args:
  engine: "pyarrow"
save_args:
  engine: "pyarrow"

validation:
  enabled: true
  thresholds:
    missing_warn_pct: 1.0
    missing_fail_pct: 5.0
    duplicate_warn_pct: 1.0
    duplicate_fail_pct: 5.0

optimization:
  lambda_DA_hat: "SpotPriceEUR_DE_LU"
  lambda_B_hat: "ImbalancePriceEUR_DE_LU"
  P_W_hat: "WindPowerRealized"
  P_W_tilde: "WindPowerForecast"
  model_mapping:
    0: Deficit
    1: Surplus
    2: Balance

transform:
  remove_classes:
    # target_classes: [Balance]
  label_mapping:
    target_classes:
      Deficit: 0
      Surplus: 1
      Balance: 2
  drop_columns:
  rename_columns:
  hot_encode:
    columns:
  drop_duplicates: true
  drop_missing_threshold: 0.1
  fill_missing:
    method: "forward" # mean, median, mode, forward, backward, interpolate, zero
  convert_types:
  normalize:
    method: "zscore" # minmax, zscore
    columns: ${datasets.training.feature_columns_flex}

training:
  datetime_column: datetime
  target_column: target_classes
  target_wasserstein: target_continuous
  fallback_class: 2
  feature_columns_fix:
    - sin_hour
    - cos_hour
    - sin_dayofweek
    - cos_dayofweek
  feature_columns_flex:
    - WindForecastError_Lag
    - WindPowerForecast_feature
    - aFRR_Down_Prices_DK_1
    - aFRR_Down_Quantity_DK_1
    - aFRR_Up_Prices_DK_1
    - aFRR_Up_Quantity_DK_1
    - aFRR_Down_Prices_DK_2
    - aFRR_Down_Quantity_DK_2
    - aFRR_Up_Prices_DK_2
    - aFRR_Up_Quantity_DK_2
    - aFRR_Down_Prices_NO_2
    - aFRR_Down_Quantity_NO_2
    - aFRR_Up_Prices_NO_2
    - aFRR_Up_Quantity_NO_2
    - aFRR_Down_Prices_NL
    - aFRR_Down_Quantity_NL
    - aFRR_Up_Prices_NL
    - aFRR_Up_Quantity_NL
    - aFRR_Down_Prices_SE_4
    - aFRR_Down_Quantity_SE_4
    - aFRR_Up_Prices_SE_4
    - aFRR_Up_Quantity_SE_4
    - mFRR_Down_Prices_AT
    - mFRR_Down_Quantity_AT
    - mFRR_Up_Prices_AT
    - mFRR_Up_Quantity_AT
    - mFRR_Up_Prices_BE
    - mFRR_Up_Quantity_BE
    - mFRR_Down_Prices_DK_2
    - mFRR_Down_Quantity_DK_2
    - mFRR_Up_Prices_DK_2
    - mFRR_Up_Quantity_DK_2
    - mFRR_Up_Prices_FR
    - mFRR_Up_Quantity_FR
    - mFRR_Down_Prices_NO_2
    - mFRR_Down_Quantity_NO_2
    - mFRR_Up_Prices_NO_2
    - mFRR_Up_Quantity_NO_2
    - mFRR_Down_Prices_NL
    - mFRR_Down_Quantity_NL
    - mFRR_Up_Prices_NL
    - mFRR_Up_Quantity_NL
    - flow_DE_LU_AT_Lag
    - flow_DE_LU_BE_Lag
    - flow_DE_LU_CH_Lag
    - flow_DE_LU_CZ_Lag
    - flow_DE_LU_DK_1_Lag
    - flow_DE_LU_DK_2_Lag
    - flow_DE_LU_FR_Lag
    - flow_DE_LU_NO_2_Lag
    - flow_DE_LU_NL_Lag
    - flow_DE_LU_PL_Lag
    - flow_DE_LU_SE_4_Lag
    - flow_AT_DE_LU_Lag
    - flow_BE_DE_LU_Lag
    - flow_CH_DE_LU_Lag
    - flow_CZ_DE_LU_Lag
    - flow_DK_1_DE_LU_Lag
    - flow_DK_2_DE_LU_Lag
    - flow_FR_DE_LU_Lag
    - flow_NO_2_DE_LU_Lag
    - flow_NL_DE_LU_Lag
    - flow_PL_DE_LU_Lag
    - flow_SE_4_DE_LU_Lag
    - SpotPriceEUR_DE_LU_Lag
    - SpotPriceEUR_AT_Lag
    - SpotPriceEUR_BE_Lag
    - SpotPriceEUR_CH_Lag
    - SpotPriceEUR_CZ_Lag
    - SpotPriceEUR_DK_1_Lag
    - SpotPriceEUR_DK_2_Lag
    - SpotPriceEUR_FR_Lag
    - SpotPriceEUR_NO_2_Lag
    - SpotPriceEUR_NL_Lag
    - SpotPriceEUR_PL_Lag
    - SpotPriceEUR_SE_4_Lag
    - generation_forecast_DE_LU
    - generation_forecast_Scheduled_Aggregated_AT
    - generation_forecast_BE
    - generation_forecast_CH
    - generation_forecast_Scheduled_Aggregated_CZ
    - generation_forecast_DK_1
    - generation_forecast_DK_2
    - generation_forecast_FR
    - generation_forecast_NO_2
    - generation_forecast_NL
    - generation_forecast_PL
    - generation_forecast_SE_4
    - forecast_Solar_DE_LU
    - forecast_Wind_Offshore_DE_LU
    - forecast_Wind_Onshore_DE_LU
    - forecast_Solar_AT
    - forecast_Wind_Onshore_AT
    - forecast_Solar_BE
    - forecast_Wind_Offshore_BE
    - forecast_Wind_Onshore_BE
    - forecast_Solar_CH
    - forecast_Wind_Onshore_CH
    - forecast_Solar_CZ
    - forecast_Solar_DK_1
    - forecast_Wind_Offshore_DK_1
    - forecast_Wind_Onshore_DK_1
    - forecast_Solar_DK_2
    - forecast_Wind_Offshore_DK_2
    - forecast_Wind_Onshore_DK_2
    - forecast_Solar_FR
    - forecast_Wind_Offshore_FR
    - forecast_Wind_Onshore_FR
    - forecast_Solar_NO_2
    - forecast_Wind_Onshore_NO_2
    - forecast_Solar_NL
    - forecast_Wind_Offshore_NL
    - forecast_Wind_Onshore_NL
    - forecast_Solar_PL
    - forecast_Wind_Onshore_PL
    - forecast_Solar_SE_4
    - forecast_Wind_Onshore_SE_4
    - Long_AT_Lag
    - Short_AT_Lag
    - Long_BE_Lag
    - Short_BE_Lag
    - Long_CH_Lag
    - Short_CH_Lag
    - Long_CZ_Lag
    - Short_CZ_Lag
    - Long_DK_1_Lag
    - Short_DK_1_Lag
    - Long_DK_2_Lag
    - Short_DK_2_Lag
    - Long_FR_Lag
    - Short_FR_Lag
    - Long_NO_2_Lag
    - Short_NO_2_Lag
    - Long_NL_Lag
    - Short_NL_Lag
    - Long_PL_Lag
    - Short_PL_Lag
    - Long_SE_4_Lag
    - Short_SE_4_Lag
    - Imbalance_Volume_AT_Lag
    - Imbalance_Volume_BE_Lag
    - Imbalance_Volume_CH_Lag
    - Imbalance_Volume_CZ_Lag
    - Imbalance_Volume_FR_Lag
    - Imbalance_Volume_NO_2_Lag
    - Imbalance_Volume_PL_Lag
    - Forecasted_Load_DE_LU
    - Forecasted_Load_AT
    - Forecasted_Load_BE
    - Forecasted_Load_CH
    - Forecasted_Load_CZ
    - Forecasted_Load_DK_1
    - Forecasted_Load_DK_2
    - Forecasted_Load_FR
    - Forecasted_Load_NO_2
    - Forecasted_Load_NL
    - Forecasted_Load_PL
    - Forecasted_Load_SE_4
    - net_transfer_forecast_DE_LU_CH
    - net_transfer_forecast_DE_LU_DK_1
    - net_transfer_forecast_DE_LU_NL
    - net_transfer_forecast_CH_DE_LU
    - net_transfer_forecast_DK_1_DE_LU
    - net_transfer_forecast_NL_DE_LU
    - offered_capacity_DE_LU_DK_1
    - offered_capacity_DE_LU_NO_2
    - offered_capacity_DK_1_DE_LU
    - offered_capacity_NO_2_DE_LU
    - scheduled_exchanges_DE_LU_AT
    - scheduled_exchanges_DE_LU_BE
    - scheduled_exchanges_DE_LU_CH
    - scheduled_exchanges_DE_LU_CZ
    - scheduled_exchanges_DE_LU_DK_1
    - scheduled_exchanges_DE_LU_DK_2
    - scheduled_exchanges_DE_LU_FR
    - scheduled_exchanges_DE_LU_NO_2
    - scheduled_exchanges_DE_LU_NL
    - scheduled_exchanges_DE_LU_PL
    - scheduled_exchanges_DE_LU_SE_4
    - scheduled_exchanges_AT_DE_LU
    - scheduled_exchanges_BE_DE_LU
    - scheduled_exchanges_CH_DE_LU
    - scheduled_exchanges_CZ_DE_LU
    - scheduled_exchanges_DK_1_DE_LU
    - scheduled_exchanges_DK_2_DE_LU
    - scheduled_exchanges_FR_DE_LU
    - scheduled_exchanges_NO_2_DE_LU
    - scheduled_exchanges_NL_DE_LU
    - scheduled_exchanges_PL_DE_LU
    - scheduled_exchanges_SE_4_DE_LU
    - ImbalancePriceEUR_DE_LU_Lag
    - ImbalanceVolume_DE_LU_Lag
    - temperature_2m_54.24N_7.72E
    - cloud_cover_54.24N_7.72E
    - wind_speed_10m_54.24N_7.72E
    - wind_direction_10m_54.24N_7.72E
    - temperature_2m_54.38N_11.62E
    - cloud_cover_54.38N_11.62E
    - wind_speed_10m_54.38N_11.62E
    - wind_direction_10m_54.38N_11.62E
    - temperature_2m_52.48N_8.54E
    - cloud_cover_52.48N_8.54E
    - wind_speed_10m_52.48N_8.54E
    - wind_direction_10m_52.48N_8.54E
    - temperature_2m_51.12N_13.14E
    - cloud_cover_51.12N_13.14E
    - wind_speed_10m_51.12N_13.14E
    - wind_direction_10m_51.12N_13.14E
    - temperature_2m_48.38N_12.30E
    - cloud_cover_48.38N_12.30E
    - wind_speed_10m_48.38N_12.30E
    - wind_direction_10m_48.38N_12.30E
    - target_continuous_lag
    - solar_delta_1h_DK_1
    - wind_offshore_delta_1h_DK_1
    - residual_load_DK_1
    - energy_balance_DK_1
    - aFRR_volumen_spread_DK_1
    - aFRR_price_spread_DK_1
    - solar_delta_1h_DE_LU
    - wind_offshore_delta_1h_DE_LU
    - residual_load_DE_LU
    - energy_balance_DE_LU
    - solar_delta_1h_DK_2
    - wind_offshore_delta_1h_DK_2
    - residual_load_DK_2
    - energy_balance_DK_2
    - mFRR_volumen_spread_DK_2
    - mFRR_price_spread_DK_2
    - aFRR_volumen_spread_DK_2
    - aFRR_price_spread_DK_2
    - solar_delta_1h_NO_2
    - wind_offshore_delta_1h_NO_2
    - residual_load_NO_2
    - energy_balance_NO_2
    - mFRR_volumen_spread_NO_2
    - mFRR_price_spread_NO_2
    - aFRR_volumen_spread_NO_2
    - aFRR_price_spread_NO_2
    - solar_delta_1h_SE_4
    - wind_offshore_delta_1h_SE_4
    - residual_load_SE_4
    - energy_balance_SE_4
    - aFRR_volumen_spread_SE_4
    - aFRR_price_spread_SE_4
    - solar_delta_1h_NL
    - wind_offshore_delta_1h_NL
    - residual_load_NL
    - energy_balance_NL
    - mFRR_volumen_spread_NL
    - mFRR_price_spread_NL
    - aFRR_volumen_spread_NL
    - aFRR_price_spread_NL
    - solar_delta_1h_PL
    - wind_offshore_delta_1h_PL
    - residual_load_PL
    - energy_balance_PL
    - solar_delta_1h_AT
    - wind_offshore_delta_1h_AT
    - residual_load_AT
    - energy_balance_AT
    - mFRR_volumen_spread_AT
    - mFRR_price_spread_AT
    - solar_delta_1h_BE
    - wind_offshore_delta_1h_BE
    - residual_load_BE
    - energy_balance_BE
    - solar_delta_1h_FR
    - wind_offshore_delta_1h_FR
    - residual_load_FR
    - energy_balance_FR
    - solar_delta_1h_CH
    - wind_offshore_delta_1h_CH
    - residual_load_CH
    - energy_balance_CH
    - solar_delta_1h_CZ
    - wind_offshore_delta_1h_CZ
    - residual_load_CZ
    - energy_balance_CZ
