dataset_name: "onlyDK1"

type: pandas.ParquetDataSet
filename: data2025.parquet
filepath: "data/processed/"
load_args:
  engine: "pyarrow"
save_args:
  engine: "pyarrow"

validation:
  enabled: true
  thresholds:
    missing_warn_pct: 1.0
    missing_fail_pct: 5.0
    duplicate_warn_pct: 1.0
    duplicate_fail_pct: 5.0

optimization:
  lambda_DA_hat: "SpotPriceEUR_DK1"
  lambda_B_hat: "ImbalancePriceEUR_DK1"
  P_W_hat: "WindPowerRealized"
  P_W_tilde: "WindPowerForecast"
  model_mapping:
    0: Deficit
    1: Surplus
    2: Balance

transform:
  remove_classes:
    # target_classes: [Balance]
  label_mapping:
    target_classes:
      Deficit: 0
      Surplus: 1
      Balance: 2
  drop_columns:
  rename_columns:
  hot_encode:
    columns:
  drop_duplicates: true
  drop_missing_threshold: 0.1
  fill_missing:
    method: "forward" # mean, median, mode, forward, backward, interpolate, zero
  convert_types:
  normalize:
    method: "zscore" # minmax, zscore
    columns: ${datasets.training.feature_columns_flex}

training:
  datetime_column: datetime
  target_column: target_classes
  fallback_class: 2
  feature_columns_fix:
    - sin_hour
    - cos_hour
    - sin_dayofweek
    - cos_dayofweek
  feature_columns_flex:
    - BalancingDemand_DK1_Lag
    - ImbalancePriceEUR_DK1_Lag
    - SpotPriceEUR_DK1_Lag
    - mFRR_UpDemandMW_DK1
    - mFRR_UpProcuredMW_DK1
    - mFRR_UpPriceEUR_DK1
    - mFRR_DownDemandMW_DK1
    - mFRR_DownProcuredMW_DK1
    - mFRR_DownPriceEUR_DK1
    - Offshore_Wind_DK1
    - Onshore_Wind_DK1
    - Solar_DK1
    - aFRR_UpDemandMW_DK1
    - aFRR_UpProcuredMW_DK1
    - aFRR_UpPriceEUR_DK1
    - aFRR_DownDemandMW_DK1
    - aFRR_DownProcuredMW_DK1
    - aFRR_DownPriceEUR_DK1
    - WindPowerForecast_feature
    - WindForecastError_Lag
    - aFRR_Down_Prices_DK_1
    - aFRR_Down_Quantity_DK_1
    - aFRR_Up_Prices_DK_1
    - aFRR_Up_Quantity_DK_1
    - flow_DK_1_DE_LU_Lag
    - flow_DK_1_DK_2_Lag
    - flow_DK_1_NO_2_Lag
    - flow_DK_1_SE_3_Lag
    - flow_DK_1_NL_Lag
    - flow_DK_1_GB_Lag
    - flow_DE_LU_DK_1_Lag
    - flow_DK_2_DK_1_Lag
    - flow_NO_2_DK_1_Lag
    - flow_SE_3_DK_1_Lag
    - flow_NL_DK_1_Lag
    - flow_GB_DK_1_Lag
    - generation_forecast_DK_1
    - forecast_Solar_DK_1
    - forecast_Wind_Offshore_DK_1
    - forecast_Wind_Onshore_DK_1
    - Long_DK_1_Lag
    - Short_DK_1_Lag
    - Imbalance_Volume_DK_1_Lag
    - Forecasted_Load_DK_1
    - Load_Error_DK_1_Lag
    - net_position_DK_1_Lag
    - net_transfer_forecast_DK_1_DE_LU
    - net_transfer_forecast_DK_1_NL
    - net_transfer_forecast_DK_1_GB
    - net_transfer_forecast_DE_LU_DK_1
    - net_transfer_forecast_NL_DK_1
    - net_transfer_forecast_GB_DK_1
    - offered_capacity_DK_1_DE_LU
    - offered_capacity_DK_1_DK_2
    - offered_capacity_DK_1_NO_2
    - offered_capacity_DK_1_SE_3
    - offered_capacity_DK_1_NL
    - offered_capacity_DE_LU_DK_1
    - offered_capacity_DK_2_DK_1
    - offered_capacity_NO_2_DK_1
    - offered_capacity_SE_3_DK_1
    - offered_capacity_NL_DK_1
    - scheduled_exchanges_DK_1_DE_LU
    - scheduled_exchanges_DK_1_DK_2
    - scheduled_exchanges_DK_1_NO_2
    - scheduled_exchanges_DK_1_SE_3
    - scheduled_exchanges_DK_1_NL
    - scheduled_exchanges_DK_1_GB
    - scheduled_exchanges_DE_LU_DK_1
    - scheduled_exchanges_DK_2_DK_1
    - scheduled_exchanges_NO_2_DK_1
    - scheduled_exchanges_SE_3_DK_1
    - scheduled_exchanges_NL_DK_1
    - scheduled_exchanges_GB_DK_1
    - temperature_2m_57.5N_8.0E
    - cloud_cover_57.5N_8.0E
    - wind_speed_10m_57.5N_8.0E
    - wind_direction_10m_57.5N_8.0E
    - temperature_2m_56.25N_8.25E
    - cloud_cover_56.25N_8.25E
    - wind_speed_10m_56.25N_8.25E
    - wind_direction_10m_56.25N_8.25E
    - temperature_2m_54.75N_8.5E
    - cloud_cover_54.75N_8.5E
    - wind_speed_10m_54.75N_8.5E
    - wind_direction_10m_54.75N_8.5E
    - temperature_2m_57.0N_9.75E
    - cloud_cover_57.0N_9.75E
    - wind_speed_10m_57.0N_9.75E
    - wind_direction_10m_57.0N_9.75E
    - temperature_2m_56.0N_9.0E
    - cloud_cover_56.0N_9.0E
    - wind_speed_10m_56.0N_9.0E
    - wind_direction_10m_56.0N_9.0E
    - temperature_2m_55.5N_9.5E
    - cloud_cover_55.5N_9.5E
    - wind_speed_10m_55.5N_9.5E
    - wind_direction_10m_55.5N_9.5E
    - temperature_2m_56.25N_10.25E
    - cloud_cover_56.25N_10.25E
    - wind_speed_10m_56.25N_10.25E
    - wind_direction_10m_56.25N_10.25E
    - temperature_2m_55.75N_9.75E
    - cloud_cover_55.75N_9.75E
    - wind_speed_10m_55.75N_9.75E
    - wind_direction_10m_55.75N_9.75E
    - temperature_2m_55.5N_10.25E
    - cloud_cover_55.5N_10.25E
    - wind_speed_10m_55.5N_10.25E
    - wind_direction_10m_55.5N_10.25E
    - temperature_2m_55.0N_9.75E
    - cloud_cover_55.0N_9.75E
    - wind_speed_10m_55.0N_9.75E
    - wind_direction_10m_55.0N_9.75E
    - target_continuous_lag
